<?php

/**
 * Implements hook_preprocess_views_view_field().
 */
function nefo_preprocessor_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  
  /**
   * View: NeFo-Abstimmungsergebnisse
   */
  if (!empty($view) && $view->name == 'nefo_view_vote_results') {
    // Average
    if ($variables['field']->options['id'] == 'value_3') {
      $average = $variables['row']->votingapi_cache_node_points_vote_average_value;
      $variables['output'] = $average;
    }
    // Proportion of positive votes
    if ($variables['field']->options['id'] == 'value_4') {
      $proportion = round(intval($variables['row']->votingapi_cache_node_points_vote_positives_value) * 100  / intval($variables['row']->votingapi_cache_node_points_vote_count_value));
      $variables['output'] = $proportion .'%';
    }
    // Proportion of negative votes
    if ($variables['field']->options['id'] == 'value_6') {
      $proportion = round(intval($variables['row']->votingapi_cache_node_points_vote_negatives_value) * -100 / intval($variables['row']->votingapi_cache_node_points_vote_count_value));
      $variables['output'] = $proportion .'%';
    }
  }
  
  /**
   * View: NeFo-Übersichtstabelle Produkte per Begriff
   */
  if (!empty($view) && $view->name == 'nefo_view_list_products_by_term') {
    if ($variables['field']->options['id'] == 'type_1') {
      $tid = intval($variables['row']->taxonomy_term_data_field_data_field_nefo_taxonomy_document_t);
      $node_type = $variables['row']->node_type;
      $variables['output'] = _nefo_preprocessor_get_product_document_icon($node_type, $tid);
    }
  }

  /**
   * View: NeFo-Block Current Products
   * Aktuelle Produkte: Stellungnahmen, Faktenblätter, Berichte, Studien, NeFo-Artikel
   */
  if (!empty($view) && $view->name == 'nefo_block_current_products') {
    // Image
    if ($variables['field']->options['id'] == 'field_nefo_slide_product_img') {
      if (empty($variables['row']->field_field_nefo_article_img) && empty($variables['row']->field_field_nefo_slide_product_img)) {
        $tid = intval($variables['row']->taxonomy_term_data_field_data_field_nefo_taxonomy_document_t);
        $nid = $variables['row']->nid;
        $node_type = $variables['row']->node_type;
        $image = _nefo_preprocessor_get_product_frontpage_image($node_type, $tid);
        $variables['output'] = l($image, "node/$nid", array('html' => TRUE));
      }
    }
    // Link
    if ($variables['field']->options['id'] == 'type') {
      $tid = intval($variables['row']->taxonomy_term_data_field_data_field_nefo_taxonomy_document_t);
      $node_type = $variables['row']->node_type;
      $variables['output'] = _nefo_preprocessor_get_product_display_link($node_type, $tid);
    }
  }
  
} //hook_preprocess_views_view_field()


/**
 * Implements hook_preprocess_page().
 */
function nefo_preprocessor_preprocess_page(&$variables) {
  // If interview content type, add custom class to title
  if ((isset($variables['node']->type)) && ($variables['node']->type == 'nefo_product_interview')) {
    $variables['title_attributes_array']['class'][] = 'nefo-product-interview-page-title';
  }

  // If nefo_news content type, add custom variable
  if ((isset($variables['node']->type)) && ($variables['node']->type == 'nefo_news')) {
    $node = node_load($variables['node']->nid);
    $output = field_view_field('node', $node, 'field_nefo_news_category', array('label' => 'hidden'));
    $variables['nefo_news_category'] = $output;
  }

  // Change title of Presse page (view "NeFo-Übersichtstabelle News per Begriff")
  if (empty($variables['node'])) {
    $current_path = drupal_get_path_alias();
    if($current_path == 'presse') {
      drupal_set_title('Presse');
    }
  }

  // If content type "nefo_product_document" or "nefo_product_article" or "", add icon to title
  if ((isset($variables['node']->type)) && ( ($variables['node']->type == 'nefo_product_document') ||
        ($variables['node']->type == 'nefo_product_article') || ($variables['node']->type == 'nefo_product_interview') ||
        ($variables['node']->type == 'nefo_news') || ($variables['node']->type == 'nefo_video') )) {
    $tid = 0;
    if ($variables['node']->type == 'nefo_product_document') {
      $item = field_get_items('node', $variables['node'], 'field_nefo_taxonomy_document');
      $tid = intval($item[0]['tid']);
    }
    elseif ($variables['node']->type == 'nefo_news') {
      $item = field_get_items('node', $variables['node'], 'field_nefo_news_category');
      $tid = intval($item[0]['tid']);
    }
    $icon = _nefo_preprocessor_get_product_document_icon($variables['node']->type, $tid, FALSE);
    if (!empty($icon)) {
      $variables['title'] = '<span class="nefo-page-title-icon">'. $icon .'</span><span class="nefo-page-title-text">'. $variables['node']->title .'</span>';
    }
  }
} //hook_preprocess_page()



function _nefo_preprocessor_get_product_document_icon($node_type, $tid, $force=TRUE) {
  $path = drupal_get_path('theme', 'ofen');
  $type = _nefo_preprocessor_get_nefo_product_type($node_type, $tid);
  $icon = '';
  switch ($type) {
        case 'nefo_product_article':
            $icon = '<img class="nefo-product-icon" alt="Artikel" title="Artikel" src="/'. $path .'/images/icons/products/Artikel.png">';
            break;
        case 'nefo_product_report':
            $icon = '<img class="nefo-product-icon" alt="Bericht" title="Bericht" src="/'. $path .'/images/icons/products/Bericht.png">';
            break;
        case 'nefo_product_factsheet':
            $icon = '<img class="nefo-product-icon" alt="Faktenblatt" title="Faktenblatt" src="/'. $path .'/images/icons/products/Faktenblatt.png">';
            break;
        case 'nefo_product_interview':
            $icon = '<img class="nefo-product-icon" alt="Interview" title="Interview" src="/'. $path .'/images/icons/products/Interview.png">';
            break;
        case 'nefo_product_opinion':
            $icon = '<img class="nefo-product-icon" alt="Stellungnahme" title="Stellungnahme" src="/'. $path .'/images/icons/products/Stellungnahme.png">';
            break;
        case 'nefo_product_study':
            $icon = '<img class="nefo-product-icon" alt="Studie" title="Studie" src="/'. $path .'/images/icons/products/Bericht.png">';
            break;
        case 'nefo_product_press_release':
            $icon = '<img class="nefo-product-icon" alt="Pressemitteilung" title="Pressemitteilung" src="/'. $path .'/images/icons/products/Pressemitteilung.png">';
            break;
        case 'nefo_video':
            $icon = '<img class="nefo-product-icon" alt="Video" title="Video" src="/'. $path .'/images/icons/products/Video.png">';
            break;
  }//switch()

  //  Icons were not provided for Workshop, News and Event
  //  Workaround: Workshop => Bericht.png, News => Pressemitteilung.png, Event => Artikel.png
  if ($force) {
    switch ($type) {
        case 'nefo_product_workshop':
            $icon = '<img class="nefo-product-icon" alt="Workshop" title="Workshop" src="/'. $path .'/images/icons/products/Bericht.png">';
            break;
        case 'nefo_news':
            $icon = '<img class="nefo-product-icon" alt="News" title="News" src="/'. $path .'/images/icons/products/Pressemitteilung.png">';
            break;
        case 'nefo_event':
            $icon = '<img class="nefo-product-icon" alt="Event" title="Event" src="/'. $path .'/images/icons/products/Artikel.png">';
            break;
    }//switch()
  }

  return $icon;
}


function _nefo_preprocessor_get_product_frontpage_image($node_type, $tid) {
  $path = drupal_get_path('theme', 'ofen');
  $type = _nefo_preprocessor_get_nefo_product_type($node_type, $tid);
  switch ($type) {
        case 'nefo_product_report':
            $image = '<img class="nefo-product-icon" alt="Bericht" title="Bericht" src="/'. $path .'/images/icons/current-products/Bericht.png">';
            break;
        case 'nefo_product_factsheet':
            $image = '<img class="nefo-product-icon" alt="Faktenblatt" title="Faktenblatt" src="/'. $path .'/images/icons/current-products/Faktenblatt.png">';
            break;
        case 'nefo_product_opinion':
            $image = '<img class="nefo-product-icon" alt="Stellungnahme" title="Stellungnahme" src="/'. $path .'/images/icons/current-products/Stellungnahme.png">';
            break;
        case 'nefo_product_study':
            $image = '<img class="nefo-product-icon" alt="Studie" title="Studie" src="/'. $path .'/images/icons/current-products/Studie.png">';
            break;
        default:
            $image = '';
  }

  return $image;
}


function _nefo_preprocessor_get_product_display_link($node_type, $tid) {
  $products = array(
      'nefo_product_report'     => array('alle Berichte', '/produkte/berichte'),
      'nefo_product_factsheet'  => array('alle Faktenblätter', '/produkte/faktenblaetter'),
      'nefo_product_opinion'    => array('alle Stellungnahmen', '/produkte/stellungnahmen'),
      'nefo_product_study'      => array('alle Studien', '/produkte/studien'),
      'nefo_product_article'      => array('alle Artikel', '/schnittstellen/produkte/artikel'),
  );

  $type = _nefo_preprocessor_get_nefo_product_type($node_type, $tid);
  $display_link = (!empty($products[$type])) ? l($products[$type][0], $products[$type][1]) : '';

  return $display_link;
}


function _nefo_preprocessor_get_nefo_product_type($node_type, $tid) {
  $type = '';

  switch ($tid) {
      // Taxonomy: NeFo-Dokument
      case 79:
        $type = 'nefo_product_report';
        break;
      case 76:
        $type = 'nefo_product_factsheet';
        break;
      case 77:
        $type = 'nefo_product_opinion';
        break;
      case 78:
        $type = 'nefo_product_study';
        break;
      // Taxonomy: NeFo-News
      case 75:
        $type = 'nefo_product_press_release';
        break;
      default:
        $type = $node_type;
  }

  return $type;
}
