<?php

/**
 * Implements hook_block_info().
 */
function nefo_blocks_builder_block_info() {
  $blocks = array();

  $blocks['nefo_footer_banner'] = array(
    'info' => t('NeFo Footer Banner'),
  );
  
  $blocks['nefo_feature_map'] = array(
    'info' => t('Researchmap'),
    'description' => t('A block to feature the research map on the frontpage'),
  );

  $blocks['nefo_newsletter2go_biodiv_news'] = array(
    'info' => t('Newsletter2Go Biodiv News'),
    'description' => t('Newsletter subscription form for Biodiv News'),
  );
  $blocks['nefo_newsletter2go_ipbes_news'] = array(
    'info' => t('Newsletter2Go IPBES News'),
    'description' => t('Newsletter subscription form for IPBES News'),
  );
  $blocks['nefo_newsletter2go_press_news'] = array(
    'info' => t('Newsletter2Go Press News'),
    'description' => t('Newsletter subscription form for Press News'),
  );
  
  $blocks['nefo_language_switch'] = array(
    'info' => t('NeFo Language Switch'),
  );
  
  $blocks['nefo_social_links_top'] = array(
    'info' => t('NeFo Social Links Top'),
  );
  $blocks['nefo_social_links_bottom'] = array(
    'info' => t('NeFo Social Links Bottom'),
  );  
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function nefo_blocks_builder_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'nefo_footer_banner':
      $block['subject'] = '';
      $block['content'] = _nefo_blocks_builder_nefo_footer_banner_content();
      break;
    case 'nefo_feature_map':
      $block['subject'] = '';
      $block['content'] = _nefo_blocks_builder_nefo_feature_map_content();
      break;
    case 'nefo_newsletter2go_biodiv_news':
      $block['subject'] = t('Biodiversity Research Newsletter');
      $block['content'] = _nefo_newsletter2go_content();
      break;
    case 'nefo_newsletter2go_ipbes_news':
      $block['subject'] = t('IPBES Newsletter');      
      $block['content'] = _nefo_newsletter2go_content(2);
      break;
    case 'nefo_newsletter2go_press_news':
      //$block['subject'] = t('Press Distribution');
      //$block['content'] = _nefo_newsletter2go_content(3);
      $block['content'] = _nefo_newsletter2go_press_news_button_content();
      break;
    case 'nefo_language_switch':
      $block['subject'] = '';
      $block['content'] = _nefo_blocks_builder_nefo_language_switch_content();
      break;
    case 'nefo_social_links_top':
      $block['subject'] = '';
      $block['content'] = _nefo_blocks_builder_nefo_social_links_content();
      break;
    case 'nefo_social_links_bottom':
      $block['subject'] = '';
      $block['content'] = _nefo_blocks_builder_nefo_social_links_content(TRUE);
      break;
  }

  return $block;
}

function _nefo_blocks_builder_nefo_footer_banner_content() {
  $output = '<div class="nefo-footer-banner">
        <div class="nefo-footer-banner-col"><div class="nefo-footer-banner-col1">
            <div class="nefo-footer-banner-col-link"><a href="/schnittstellen/produkte"></a></div>
            <a href="/schnittstellen/produkte">'. t('NeFo Products') .'</a>
        </div></div>
        <div class="nefo-footer-banner-col"><div class="nefo-footer-banner-col2">
            <div class="nefo-footer-banner-col-link"><a href="/schnittstellen/workshops"></a></div>
            <a href="/schnittstellen/produkte/workshops">'. t('Workshops') .'</a>
        </div></div>
        <div class="nefo-footer-banner-col"><div class="nefo-footer-banner-col3">
            <div class="nefo-footer-banner-col-link"><a href="/newsletter"></a></div>
            <a href="/newsletter">'. t('Newsletter') .'</a>
        </div></div>
        <div class="nefo-footer-banner-col"><div class="nefo-footer-banner-col4">
            <div class="nefo-footer-banner-col-link"><a href="/blogs"></a></div>
            <a href="/blogs">'. t('NeFo Blogs') .'</a>
        </div></div>
      </div>';
  
  return $output;
}

function _nefo_blocks_builder_nefo_feature_map_content() {
  $map_url = 'forschung/forschungsakteure/forschungsatlas';
  $image = array(
    '#theme' => 'image_formatter',
    '#item' => array(
      'uri' => 'public://products/slideshow/nefo_forschungsatlas_screenshoot_16-03-2016.jpg',
      'alt' => t('example image of research map.'),
    ),
    '#path' => array(
      'path' => $map_url,
      'options' => array('html' => TRUE), // Optional.
    ),
  );

  $block = array(
    'image' => array(
      '#type' => 'container',
      '#attributes' => array('class' => array('feature-map-img')),
      'title' => array(
        '#type' => 'markup',
        '#markup' => '<h2>' . t('Feature') . '</h2>',
      ),
      'heading' => array(
        '#type' => 'markup',
        '#markup' => '<h3>' . t('Research Map') . '</h3>',
      ),
      'content' => $image,
    ),
    'message' => array(
      '#type' => 'container',
      '#attributes' => array('class' =>array('feature-map-text')),
      'title' => array(
        '#type' => 'markup',
        '#markup' => '<h2>' . t('Feature') . '</h2>',
      ),
      'heading' => array(
        '#type' => 'markup',
        '#markup' => '<h3>' . t('Research Map') . '</h3>',
      ),
      'description' => array(
        '#type' => 'markup',
        '#markup' => '<p>' . 
            'Der NeFo-Atlas der Forschungsakteure enthält aktuell mehr als 1.300 Einträge. '.
            'Diese helfen Ihnen, die passenden ExpertInnen für Ihre Fragen zur biologischen '.
            'Vielfalt in universitären und außer-universitären Forschungsinstituten sowie NGOs, '.
            'Unternehmen und öffentlichen Verwaltungen zu finden.' . 
          '</p>',
      ),
      'button' => array(
        '#type' => 'container',
        '#attributes' => array('class' =>array('btn btn--blue')),
        'link#' =>array(
          '#type' => 'link',
          '#title' => t('zum Forschungsatlas'),
          '#href' => $map_url,
        ),
      ),
    ),
  );
  return $block;
}

// Newsletter2Go
function _nefo_newsletter2go_content($type=1) {
  switch($type) {
    // IPBES-Newsletter
    case 2:
        $code = '806875c0512e5dec868db1f00057ece9fba0eca0a3c4d73075b9ef6897e983f2$11629';
        $label = 'Zum Newsletter anmelden';
        break;
    // Presseverteiler
    case 3:
        $code = '24305dcf21fdb8f36ff3507cfd40ebbf9bbaf4e6b40fbb2d2544ea2c8acf7306$11628';
        $label = 'Zum Presseverteiler anmelden';
        break;
    //Biodivdersitätsforschungs-Newsletter
    default:        
        $code = '3e8f7bb4d0700aa8605dc2eadc318fadbc6ccd9932ef6fc12d84778fb6f5b10b$11630';
        $label = 'Zum Newsletter anmelden';
  }
  
  $output = '<form id="nl2go--form" action="https://app.newsletter2go.com/de/recipients/index/subscribe/" method="post" accept-charset="utf-8">
<table border="0"><tbody>
<tr><td align="left" style="padding-right: 8px">E-Mail*
    </td>
    <td>
        <input type="text" name="nl2go--mail" id="nl2go--mail" style="background: #f4f4f4; border: 1px solid #cccccc; padding: 2px; width: 250px;">
    </td>
</tr>
<tr><td align="left" style="padding-right: 8px">Vorname
    </td>
    <td>
        <input type="text" name="nl2go--firstname" id="nl2go--firstname" style="background: #f4f4f4; border: 1px solid #cccccc; padding: 2px; width: 250px;">
    </td>
</tr>
<tr><td align="left" style="padding-right: 8px">Nachname
    </td>
    <td>
        <input type="text" name="nl2go--lastname" id="nl2go--lastname" style="background: #f4f4f4; border: 1px solid #cccccc; padding: 2px; width: 250px;">
    </td>
</tr>
<tr><td align="left" style="padding-right: 8px">Institution
    </td>
    <td>
        <input type="text" name="nl2go--60805" id="nl2go--60805" style="background: #f4f4f4; border: 1px solid #cccccc; padding: 2px; width: 250px;">
    </td>
</tr>
<tr>
    <td colspan="2" align="center"><input type="submit" value="'. $label .'" name="nl2go--submit" id="nl2go--submit" class="nl2go--submit" style="cursor: pointer; border: 1px solid rgb(169, 192, 65); border-radius: 3px 3px 3px 3px; font-weight: bold; text-align: center; color: rgb(255, 255, 255); background-color: rgb(169, 192, 65); background-image: -moz-linear-gradient(center top , rgb(169, 192, 65), rgb(169, 192, 65)); padding: 4px 8px;  font-size: 100%; margin-top: 8px;width: 100%;">
<input type="hidden" name="nl2go--key" id="nl2go--key" value="'. $code .'"><noscript><a href="https://www.newsletter2go.de/newsletter-erstellen/" title="Newsletter erstellen mit Newsletter2Go">Newsletter erstellen mit Newsletter2Go</a></noscript>
    </td>
</tr>
</tbody></table>
</form>';

    return $output;
}

// Presseverteiler - Button only
function _nefo_newsletter2go_press_news_button_content() {
    $output = '<form id="nl2go--form" action="/presse/presseverteiler" method="post" accept-charset="utf-8">
<table border="0"><tbody>
<tr>
    <td align="center">
        <input type="submit" value="Zum Presseverteiler anmelden" name="nl2go--submit" id="nl2go--submit" style="cursor: pointer; border: 1px solid rgb(169, 192, 65); border-radius: 3px 3px 3px 3px; font-weight: bold; text-align: center; color: rgb(255, 255, 255); background-color: rgb(169, 192, 65); background-image: -moz-linear-gradient(center top , rgb(169, 192, 65), rgb(169, 192, 65)); padding: 4px 8px;  font-size: 100%; margin-top: 8px;width: 100%;">
    </td>
</tr>
</tbody></table>
</form>';
    
  return $output;
}

// Language Switch DE EN
function _nefo_blocks_builder_nefo_language_switch_content() {
  $output = '<ul class="menu">
<li class="first leaf"><a href="/" title="Deutsch">DE</a></li>
<li class="last leaf"><a href="/en/" title="English">EN</a></li>
</ul>';

  return $output;
}

// Social Links
function _nefo_blocks_builder_nefo_social_links_content($bottom=FALSE) {
  $output = ($bottom) ? '<ul class="nefo-social-links-bottom">' : '<ul class="nefo-social-links-top">';
  $output .= '<li class="youtube">
        <a href="https://www.youtube.com/channel/UCTdzrOkdcGvLzCx2YX2JW1g" title="'. t('NeFo on YouTube') .'" target="_blank">
            <i class="fa fa-youtube" aria-hidden="true"></i>
        </a>
    </li>
    <li class="twitter">
        <a href="https://twitter.com/ne_fo" title="'. t('NeFo on Twitter') .'" target="_blank">
            <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
    </li>';
  if ($bottom) {
    $output .= '<li class="nefo-social-link-contact">
            <a href="/kontakt" title="'. t('Contact') .'">
                <i>'. t('Contact') .'</i>
            </a>
        </li>';
  }
  $output .= '</ul>';

  return $output;
}
